"""empty message

Revision ID: b30dec96abd3
Revises: ca6c2cbc554d
Create Date: 2020-05-07 23:12:16.365159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b30dec96abd3'
down_revision = 'ca6c2cbc554d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('borough', sa.String(), nullable=False),
    sa.Column('photograph', sa.String(), nullable=False),
    sa.Column('img_description', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('latlng', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('cuisine', sa.String(), nullable=False),
    sa.Column('operating_hours', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
